menu:
  Home: /
  Archives: /archives

widgets:
  - search
  - category
  - tag
  - twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

fancybox: true

google_analytics:
rss: